### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by kFxDaKing** [ashleykleynhans/runpod-worker-a1111#30]
Hello, im on serverless runpod with 24gb vram, when im generating sdxl, then everything is okay, when i switch to flux1-dev i get this error:

{
  "delayTime": 18625,
  "error": "OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB. GPU 0 has a total capacty of 23.54 GiB of which 17.75 MiB is free. Process 333813 has 23.52 GiB memory in use. Of the allocated memory 23.01 GiB is allocated by PyTorch, and 50.19 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF",
  "executionTime": 8497,
  "id": "9bfbc544-9a7c-4600-98f9-9f2b97906cc0-e2",
  "output": {
    "output": {
      "body": "",
      "detail": "",
      "error": "OutOfMemoryError",
      "errors": "CUDA out of memory. Tried to allocate 58.00 MiB. GPU 0 has a total capacty of 23.54 GiB of which 17.75 MiB is free. Process 333813 has 23.52 GiB memory in use. Of the allocated memory 23.01 GiB is allocated by PyTorch, and 50.19 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"
    }
  },
  "status": "FAILED",
  "workerId": "fmxicylcfgouqs"
}

Any ideas, why is thisn happening and how can i solve it?

**Comment by ashleykleynhans** [comment]
You are running out of VRAM, you need to enable a larger GPU type than 24GB.

**Comment by ashleykleynhans** [comment]
Maybe you need to tweak the A1111 startup settings in the [start.sh](https://github.com/ashleykleynhans/runpod-worker-a1111/blob/main/start.sh) script.

**Comment by kFxDaKing** [comment]
fixed by using fp16 version of flux instead of fp32
